# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
podfile: Example/Podfile
xcode_project: Example/InfoView.xcodeproj
xcode_scheme: InfoView-Example
xcode_sdk: iphonesimulator9.3
